site_name: Cobra Docs
theme:
  name: material
  features:
    - navigation.instant
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
nav:
  - General:
      - Home: index.md
      - Overview: general/overview.md
  - First steps:
      - Installation: first/installation.md
      - Quick start: first/quickstart.md
