site_name: Cobra Docs
theme:
  name: material
  logo: imgs/cobradocs.png
  favicon: imgs/favicon.ico
  palette:  
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
      guess_lang: false
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
nav:
  - General:
      - Overview: index.md
      - Cobra's Mission: general/mission.md
      - Support Us: general/support.md
  - First steps:
      - Installation: first/installation.md
      - Quick start: first/quickstart.md
  - Cobra:
      - CobraRouter: markets/cobrarouter.md
      - PumpFun: markets/pumpfun.md
      - PumpSwapAMM: markets/pumpswapamm.md
      - MeteoraDAMM1: markets/meteoradamm1.md
      - MeteoraDAMM2: markets/meteoradamm2.md
      - MeteoraDLMM: markets/meteoradlmm.md
      - Meteora DBC: markets/meteoradbc.md
      - RaydiumAMMV4: markets/raydiumammv4.md
      - RaydiumCLMM: markets/raydiumclmm.md
      - RaydiumDLMM: markets/raydiumdlmm.md
      - Raydium Launchpad: markets/raydiumlaunchpad.md
      - CobraNET: markets/cobranet.md
      - CobraWallets: markets/cobrawallets.md
    